---
version: 0.0.6
slug: netlify-dns
name: Netlify DNS
description: >-
  Use Netlify DNS for your Home Assistant instance
url: https://github.com/CodeFoodPixels/homeassistant-addons/tree/main/netlify-dns
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
hassio_api: true
init: false
map:
  - ssl:rw
options:
  domain: null
  subdomain: null
  token: null
  lets_encrypt:
    accept_terms: false
    algo: secp384r1
    certfile: fullchain.pem
    keyfile: privkey.pem
  seconds: 300
schema:
  domain: str
  subdomain: str
  token: str
  lets_encrypt:
    accept_terms: bool
    algo: list(rsa|prime256v1|secp384r1)
    certfile: str
    keyfile: str
  seconds: int
  ip: str?
startup: services
