---
version: 0.0.8
slug: netlify-dns
name: Netlify DNS
description: >-
  Use Netlify DNS for your Home Assistant instance
url: https://github.com/CodeFoodPixels/homeassistant-addons/tree/main/netlify-dns
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
hassio_api: true
init: false
image: "ghcr.io/codefoodpixels/homeassistant-addon-netlify-dns-{arch}"
map:
  - ssl:rw
options:
  domain: null
  subdomain: null
  token: null
  seconds: 300
schema:
  domain: str
  subdomain: str
  token: str
  seconds: int
  ip: str?
startup: services
